package me.decce.transformingbase.core.interop.dbus;

import me.decce.transformingbase.core.ProgressPeekCore;
import me.decce.transformingbase.core.ProgressStatus;
import me.decce.transformingbase.core.interop.NativeString;
import me.decce.transformingbase.core.interop.ProgressOperator;
import org.lwjgl.BufferUtils;
import org.lwjgl.PointerBuffer;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.system.MemoryUtil;

import java.io.IOException;
import java.nio.DoubleBuffer;
import java.nio.IntBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;

public class DBusProgressOperator implements ProgressOperator {
    public static final String DEFAULT_APP_NAME = "Minecraft with ProgressPeek";
    public static final String DEFAULT_CLASS_NAME = "me.decce.progresspeek";

    private DBusCommunicationThread thread;
    private long glfwWindow;
    private String className;
    private String appName;
    private boolean desktopFileGenerated;

    @Override
    public void preInitialize() {
        appName = getAppName();
        className = getClassName();
        if (!desktopFileGenerated) {
            desktopFileGenerated = true;

            String xdgDataHome = System.getenv("XDG_DATA_HOME");
            Path path;
            if (xdgDataHome != null && !xdgDataHome.isEmpty()) {
                path = Paths.get(xdgDataHome, "applications");
            } else {
                path = Paths.get(System.getProperty("user.home"), ".local", "share", "applications");
            }
            var baseName = className + ".desktop";
            var tempPath = path.resolve(baseName + ".tmp");
            var finalPath = path.resolve(baseName);
            try {
                // Instead of directly writing to the target path, we write to a temp file first, then move it to the target, which works more reliably
                Files.writeString(tempPath, generateDummyDesktopContent(), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
                Files.move(tempPath, finalPath, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
                finalPath.toFile().deleteOnExit();
            } catch (IOException e) {
                ProgressPeekCore.LOGGER.error("Failed to create desktop file!", e);
            }
        }

        GLFW.glfwWindowHintString(GLFW.GLFW_X11_CLASS_NAME, className);
        GLFW.glfwWindowHintString(GLFW.GLFW_X11_INSTANCE_NAME, className);
        GLFW.glfwWindowHintString(GLFW.GLFW_WAYLAND_APP_ID, className);

        thread = new DBusCommunicationThread(className);
        thread.start();
    }

    @Override
    public void initialize(long glfwWindow) {
        if (!desktopFileGenerated) {
            preInitialize();
        }
        if (this.glfwWindow != glfwWindow) {
            this.glfwWindow = glfwWindow;
            // The thread might not have been initialized at this point, if on an older version of Forge which does not load ImmediateWindowProvider from mods
            if (thread != null) {
                thread.set(ProgressStatus.NONE, 0, true); // Progress is persisted across launches - reset to 0
            }
        }
    }

    @Override
    public void setStatus(ProgressStatus status) {
        if (thread != null) {
            thread.set(status);
        }
    }

    @Override
    public void setValue(int percentage) {
        if (thread != null) {
            thread.set(percentage);
        }
    }

    @Override
    public void requestAttention() {
        if (this.glfwWindow != 0L) {
            GLFW.glfwRequestWindowAttention(this.glfwWindow);
        }
    }

    private String getAppName() {
        var raw = ProgressPeekCore.config.linuxAppName;
        if (raw.isEmpty()) {
            return DEFAULT_APP_NAME;
        }
        return raw;
    }

    private String getClassName() {
        var raw = ProgressPeekCore.config.linuxAppId;
        if (raw.isEmpty()) {
            return DEFAULT_CLASS_NAME;
        }
        return raw;
    }

    private String generateDummyDesktopContent() {
        return """
            # Autogenerated by Progress Peek mod for progress display
            [Desktop Entry]
            Type=Application
            Version=1.0
            NoDisplay=true
            StartupWMClass=""" + className +
            "\nName=" + appName;
    }
}
