name: Publish to CurseForge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Publish Mod to CurseForge
        run: ./gradlew buildAndCollect publishAllCurseForge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}